[package]
name = "starkprivacy_security"
version.workspace = true
edition.workspace = true

[dependencies]
starknet.workspace = true

[dev-dependencies]
snforge_std.workspace = true
assert_macros.workspace = true

[lib]

[[target.starknet-contract]]
sierra = true

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
